# Generated by Django 6.0.6 on 2026-07-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblRole',
            fields=[
                ('role_id', models.AutoField(db_column='RoleId', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='RoleName', max_length=30, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_column='UpdatedOn', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'TblRole',
            },
        ),
        migrations.CreateModel(
            name='TblSpecialization',
            fields=[
                ('specialization_id', models.AutoField(db_column='SpecializationId', primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(db_column='SpecializationName', max_length=30, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_column='UpdatedOn', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
            options={
                'db_table': 'TblSpecialization',
            },
        ),
        migrations.CreateModel(
            name='TblStaff',
            fields=[
                ('staff_id', models.AutoField(db_column='StaffId', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='FullName', max_length=100)),
                ('gender', models.CharField(db_column='Gender', max_length=1)),
                ('joining_date', models.DateField(blank=True, db_column='JoiningDate', null=True)),
                ('address_line_1', models.CharField(blank=True, db_column='Address Line 1', max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, db_column='Address Line 2', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, db_column='Pincode', max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, db_column='MobileNumber', max_length=20, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('user_name', models.CharField(db_column='UserName', max_length=30, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_column='UpdatedOn', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('role_id', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.PROTECT, to='administrator.tblrole')),
            ],
            options={
                'db_table': 'TblStaff',
            },
        ),
        migrations.CreateModel(
            name='TblDoctor',
            fields=[
                ('doctor_id', models.AutoField(db_column='DoctorId', primary_key=True, serialize=False)),
                ('consultation_fee', models.DecimalField(db_column='ConsultationFee', decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='CreatedOn', null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_column='UpdatedOn', null=True)),
                ('updated_by', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('specialization_id', models.ForeignKey(db_column='SpecializationId', on_delete=django.db.models.deletion.PROTECT, to='administrator.tblspecialization')),
                ('staff_id', models.ForeignKey(db_column='StaffId', on_delete=django.db.models.deletion.CASCADE, to='administrator.tblstaff')),
            ],
            options={
                'db_table': 'TblDoctor',
            },
        ),
    ]
