# Generated by Django 6.0.6 on 2026-09-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('labtechnician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('lab_test_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TblLabTestCategory',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(db_column='DoctorId', on_delete=django.db.models.deletion.CASCADE, to='administrator.tbldoctor')),
            ],
            options={
                'db_table': 'TblAppointment',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('lab_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_min_range', models.CharField(max_length=50)),
                ('reference_max_range', models.CharField(max_length=50)),
                ('sample_required', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('lab_test_category', models.ForeignKey(db_column='LabTestCategoryId', on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='labtechnician.labtestcategory')),
            ],
            options={
                'db_table': 'TblLabTest',
            },
        ),
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('lab_test_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(db_column='AppointmentId', on_delete=django.db.models.deletion.CASCADE, to='labtechnician.appointment')),
                ('assigned_lab_technician', models.ForeignKey(blank=True, db_column='AssignedLabTechnicianId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnician.labtechnician')),
                ('lab_test', models.ForeignKey(db_column='LabTestId', on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtest')),
            ],
            options={
                'db_table': 'TblLabTestPrescription',
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('lab_test_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_value', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='lab_results/')),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Verified', 'Verified')], default='Completed', max_length=20)),
                ('lab_technician', models.ForeignKey(db_column='LabTechnicianId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnician.labtechnician')),
                ('lab_test_prescription', models.OneToOneField(db_column='LabTestPrescriptionId', on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtestprescription')),
            ],
            options={
                'db_table': 'TblLabTestResult',
            },
        ),
    ]
