# Generated by Django 4.2.30 on 2026-07-20 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblMedicine',
            fields=[
                ('MedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=255)),
                ('MedicineForm', models.CharField(max_length=50)),
                ('CapsulesPerStrip', models.IntegerField(blank=True, null=True)),
                ('StripPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BaseUnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ManufacturingDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('IsActive', models.IntegerField(default=1)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TblMedicine',
            },
        ),
        migrations.CreateModel(
            name='TblMedicineCategory',
            fields=[
                ('MedicineCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineCategoryName', models.CharField(max_length=100, unique=True)),
                ('IsActive', models.IntegerField(default=1)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TblMedicineCategory',
            },
        ),
        migrations.CreateModel(
            name='TblPrescriptionBill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentId', models.IntegerField()),
                ('PatientId', models.IntegerField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('IsPaid', models.IntegerField(default=0)),
                ('IsActive', models.IntegerField(default=1)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TblPrescriptionBill',
            },
        ),
        migrations.CreateModel(
            name='TblPrescriptionBillItem',
            fields=[
                ('BillItemId', models.AutoField(primary_key=True, serialize=False)),
                ('StripsBilled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('CapsulesBilled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('FlatUnitsBilled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ItemCalculatedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsActive', models.IntegerField(default=1)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('BillId', models.ForeignKey(db_column='BillId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacist.tblprescriptionbill')),
                ('MedicineId', models.ForeignKey(db_column='MedicineId', on_delete=django.db.models.deletion.PROTECT, to='pharmacist.tblmedicine')),
            ],
            options={
                'db_table': 'TblPrescriptionBillItem',
            },
        ),
        migrations.CreateModel(
            name='TblMedicineStock',
            fields=[
                ('MedicineStockId', models.AutoField(primary_key=True, serialize=False)),
                ('TotalUnitsRemaining', models.IntegerField(default=0)),
                ('ReOrderLevel', models.IntegerField(default=10)),
                ('IsActive', models.IntegerField(default=1)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('MedicineId', models.OneToOneField(db_column='MedicineId', on_delete=django.db.models.deletion.PROTECT, to='pharmacist.tblmedicine')),
            ],
            options={
                'db_table': 'TblMedicineStock',
            },
        ),
        migrations.AddField(
            model_name='tblmedicine',
            name='MedicineCategoryId',
            field=models.ForeignKey(db_column='MedicineCategoryId', on_delete=django.db.models.deletion.PROTECT, to='pharmacist.tblmedicinecategory'),
        ),
    ]
