# Generated by Django 6.0.6 on 2026-09-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblmedicine',
            options={'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='tblmedicinecategory',
            options={'verbose_name': 'Medicine Category', 'verbose_name_plural': 'Medicine Categories'},
        ),
        migrations.AlterModelOptions(
            name='tblmedicinestock',
            options={'verbose_name': 'Medicine Stock', 'verbose_name_plural': 'Medicine Stocks'},
        ),
        migrations.AlterModelOptions(
            name='tblprescriptionbill',
            options={'verbose_name': 'Prescription Bill', 'verbose_name_plural': 'Prescription Bills'},
        ),
        migrations.AlterModelOptions(
            name='tblprescriptionbillitem',
            options={'verbose_name': 'Prescription Bill Item', 'verbose_name_plural': 'Prescription Bill Items'},
        ),
    ]
